INSERT INTO watches (
  brand,
  model,
  title,
  reference,
  year,
  condition,
  box_papers,
  movement,
  case_size,
  material,
  dial_color,
  bracelet_material,
  public_price,
  currency,
  availability,
  visibility,
  publication_status,
  category,
  tags,
  featured,
  hype,
  new_arrival,
  description,
  public_images,
  supplier_name,
  supplier_url,
  source_url,
  supplier_price,
  acquisition_cost,
  import_status,
  internal_notes,
  slug
) VALUES
(
  'Rolex',
  'Cosmograph Daytona',
  'Rolex Cosmograph Daytona 116500LN',
  '116500LN',
  2023,
  'excellent',
  'Full set',
  'Automatic chronograph',
  '40 mm',
  'Oystersteel / Cerachrom',
  'White',
  'Oystersteel',
  29500.00,
  'CHF',
  'available',
  'public',
  'published',
  'Rolex',
  '["Rolex", "Daytona", "Hype pieces"]'::jsonb,
  true,
  true,
  true,
  'White dial Daytona with full set presentation. Availability and final price are confirmed manually before payment instructions are issued.',
  '["/images/hero/ocean-dark.jpg"]'::jsonb,
  'Private Geneva source',
  'https://supplier-private.example/daytona',
  'https://source-private.example/listing/daytona',
  27400.00,
  28000.00,
  'seeded',
  'Seed private data. Must never appear in public responses.',
  'rolex-cosmograph-daytona-116500ln'
),
(
  'Patek Philippe',
  'Aquanaut',
  'Patek Philippe Aquanaut 5167A-001',
  '5167A-001',
  2021,
  'very_good',
  'Box and papers',
  'Automatic',
  '40.8 mm',
  'Stainless steel / rubber',
  'Black',
  'Rubber',
  52500.00,
  'CHF',
  'reserved',
  'public',
  'published',
  'Patek Philippe',
  '["Patek Philippe", "Aquanaut", "Hype pieces"]'::jsonb,
  true,
  true,
  false,
  'Request-based reserved listing. A new availability check is required before any sale can proceed.',
  '["/images/hero/forest-dark.jpg"]'::jsonb,
  'Private Zurich source',
  'https://supplier-private.example/aquanaut',
  'https://source-private.example/listing/aquanaut',
  49600.00,
  50200.00,
  'seeded',
  'Seed margin and source notes remain admin-only.',
  'patek-philippe-aquanaut-5167a-001'
),
(
  'Audemars Piguet',
  'Royal Oak Selfwinding',
  'Audemars Piguet Royal Oak Selfwinding 15500ST.OO.1220ST.01',
  '15500ST.OO.1220ST.01',
  2020,
  'excellent',
  'Full set',
  'Automatic',
  '41 mm',
  'Stainless steel',
  'Blue',
  'Stainless steel',
  39800.00,
  'CHF',
  'available',
  'public',
  'published',
  'Audemars Piguet',
  '["Audemars Piguet", "Royal Oak", "Hype pieces"]'::jsonb,
  true,
  true,
  false,
  'Blue dial Royal Oak listed for manual request. KYC and payment review may be required before completion.',
  '["/images/hero/forest-dark2.jpg"]'::jsonb,
  'EU private collection',
  'https://supplier-private.example/royal-oak',
  'https://source-private.example/listing/royal-oak',
  37100.00,
  37950.00,
  'seeded',
  'Seed compliance review note. Internal only.',
  'audemars-piguet-royal-oak-selfwinding-15500st-oo-1220st-01'
)
ON CONFLICT (slug) DO NOTHING;
